sm6125-common: comment out camera props
Conflicts with ANXCam package props:

error: found duplicate sysprop assignments:
vendor.camera.aux.packagelist=org.codeaurora.snapcam,com.android.camera
vendor.camera.aux.packagelist=com.android.camera,app.grapheneos.camera
error: found duplicate sysprop assignments:
persist.vendor.camera.privapp.list=org.codeaurora.snapcam,com.android.camera
persist.vendor.camera.privapp.list=com.android.camera,app.grapheneos.camera

error: found duplicate sysprop assignments:
persist.vendor.camera.privapp.list=org.codeaurora.snapcam,com.android.camera
persist.vendor.camera.privapp.list=com.android.camera,app.grapheneos.camera

Signed-off-by: Flopster101 <nahuelgomez329@gmail.com>