sm6125-common: Rename Dolby app to XiaomiDolbySM6125
To avoid a conflict with EvoX's Dolby on hardware/xiaomi.

[100% 38/38] analyzing Android.bp files and generating ninja file at out/soong/build.lineage_ginkgo.ninja
FAILED: out/soong/build.lineage_ginkgo.ninja
cd "$(dirname "out/host/linux-x86/bin/soong_build")" && BUILDER="$PWD/$(basename "out/host/linux-x86/bin/soong_build")" && cd / && env -i  "$BUILDER"     --top "$TOP"     --soong_out "out/soong"     --out "out"     --soong_variables out/soong/soong.lineage_ginkgo.variables -o out/soong/build.lineage_ginkgo.ninja -l out/.module_paths/Android.bp.list --available_env out/soong/soong.environment.available --used_env out/soong/soong.environment.used.lineage_ginkgo.build Android.bp
error: device/xiaomi/sm6125-common/dolby/Android.bp:8:1: module "XiaomiDolby" variant "android_common": found in multiple namespaces(hardware/xiaomi and device/xiaomi/sm6125-common) when including in system partition
00:57:52 soong bootstrap failed with: exit status 1
ninja: build stopped: subcommand failed.

failed to build some targets (37 seconds) ####

I could also just use that one, but I prefer to maintain it here.

Signed-off-by: Flopster101 <nahuelgomez329@gmail.com>