sm6125-common: Do not include private keys folder
It's already included by the build system.

Causes this strange error otherwise:

[100% 284/284] analyzing Android.bp files and generating ninja file at out/soong/build.lineage_ginkgo.ninja
FAILED: out/soong/build.lineage_ginkgo.ninja
cd "$(dirname "out/host/linux-x86/bin/soong_build")" && BUILDER="$PWD/$(basename "out/host/linux-x86/bin/soong_build")" && cd / && env -i  "$BUILDER"     --top "$TOP"     --soong_out "out/soong"     --out "out"     --soong_variables out/soong/soong.lineage_ginkgo.variables -o out/soong/build.lineage_ginkgo.ninja --kati_suffix -lineage_ginkgo --kati_enabled -l out/.module_paths/Android.bp.list --available_env out/soong/soong.environment.available --used_env out/soong/soong.environment.used.lineage_ginkgo.build Android.bp
error: system/sepolicy/mac_permissions/Android.bp:36:1: module "plat_mac_permissions.xml" variant "android_common": source path "vendor/lineage-priv/keys/ vendor/lineage-priv/keys" does not exist
error: system/sepolicy/mac_permissions/Android.bp:36:1: module "plat_mac_permissions.xml" variant "android_common": source path "vendor/lineage-priv/keys/ vendor/lineage-priv/keys" does not exist
02:46:23 soong bootstrap failed with: exit status 1

Signed-off-by: Flopster101 <nahuelgomez329@gmail.com>